# Generated by Django 6.0.4 on 2026-04-28 02:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = []

    FORWARD_SQL = """
        CREATE TABLE USER_ACCOUNT (
            user_id UUID PRIMARY KEY DEFAULT uuidv7(),
            username VARCHAR(100) UNIQUE NOT NULL,
            password VARCHAR(255) NOT NULL
        );

        CREATE TABLE ROLE (
            role_id UUID PRIMARY KEY DEFAULT uuidv7(),
            role_name VARCHAR(50) UNIQUE NOT NULL
        );

        CREATE TABLE ACCOUNT_ROLE (
            role_id UUID,
            user_id UUID,
            PRIMARY KEY (user_id, role_id),
            FOREIGN KEY (role_id) REFERENCES ROLE(role_id) ON DELETE CASCADE,
            FOREIGN KEY (user_id) REFERENCES USER_ACCOUNT(user_id) ON DELETE CASCADE
        );
    """

    REVERSE_SQL = """
        DROP TABLE IF EXISTS ACCOUNT_ROLE;
        DROP TABLE IF EXISTS ROLE;
        DROP TABLE IF EXISTS USER_ACCOUNT;
    """

    operations = [migrations.RunSQL(sql=FORWARD_SQL, reverse_sql=REVERSE_SQL)]
