# Generated by Django 6.0.4 on 2026-04-30 10:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_create_schema_and_ddl'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('user_id', models.UUIDField(db_column='user_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='username', max_length=100, unique=True)),
                ('password', models.CharField(db_column='password', max_length=255)),
            ],
            options={
                'db_table': 'USER_ACCOUNT',
                'managed': False,
            },
        ),
    ]
