# Generated by Django 6.0.4 on 2026-04-28 02:11

from django.db import migrations


class Migration(migrations.Migration):
    # dependencies = [("events", "0001_initial")]
    dependencies = []

    FORWARD_SQL = """
        CREATE TABLE ARTIST (
            artist_id UUID PRIMARY KEY DEFAULT uuidv7(),
            name VARCHAR(100) NOT NULL,
            genre VARCHAR(100)
        );

        CREATE TABLE EVENT_ARTIST (
            event_id UUID,
            artist_id UUID,
            role VARCHAR(100),
            FOREIGN KEY (artist_id) REFERENCES ARTIST(artist_id)
        );

        CREATE TABLE TICKET_CATEGORY (
            category_id UUID PRIMARY KEY DEFAULT uuidv7(),
            category_name VARCHAR(50) NOT NULL,
            quota INTEGER NOT NULL CHECK (quota > 0),
            price NUMERIC(12,2) NOT NULL CHECK (price >= 0),
            tevent_id UUID NOT NULL
        );
    """

    # NOTE add to events later
    #             FOREIGN KEY (event_id) REFERENCES EVENT(event_id),

    REVERSE_SQL = """
        DROP TABLE IF EXISTS TICKET_CATEGORY;
        DROP TABLE IF EXISTS EVENT_ARTIST;
        DROP TABLE IF EXISTS ARTIST;
    """

    operations = [migrations.RunSQL(sql=FORWARD_SQL, reverse_sql=REVERSE_SQL)]
